apiVersion: v1
kind: Config
clusters:
  - name: kubernetes-playground
    cluster:
      certificate-authority: /etc/kubernetes/pki/ca.crt
      server: https://kubernetes-playground:6443
contexts:
  - name: kube-admin@kubernetes-playground
    context:
      cluster: kubernetes-playground
      user: kube-admin
      namespace: default
users:
  - name: kube-admin
    user:
      client-certificate: /etc/kubernetes/pki/admin.crt
      client-key: /etc/kubernetes/pki/admin.key

# Commands to configure/edit the kubeconfig file

$ kubectl config view
$ kubectl config view --kubeconfig=my-custom-config
$ kubectl config use-context prod-user@production