apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devuser-developer-binding
  namespace: blue # If you want the role-binding to exist in a particular namespace.
subjects:
  - kind: User
    name: dev-user
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer
  apiGroup: rbac.authorization.k8s.io

# Related Commands

$ kubectl get rolebindings
$ kubectl describe rolebinding devuser-developer-binding
