apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_HOST: bXlzcWw= # echo -n 'mysql' | base64
  DB_User: cm9vdA== # echo -n 'mysql' | base64
  DB_Password: cGFzc3dvcmQ= # echo -n 'password' | base64
