apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    vers: ["list", "get", "create", "update", "delete"]
    resourceNames: ["blue", "orange"] # giving access to only certain pods in the namespace
  - apiGroups: [""]
    resources: ["ConfigMap"]
    verbs: ["create"]

# Related Commands

$ kubectl get roles
$ kubectl describe role developer

# Check if you have access to particular resource

$ kubectl auth can-i create deployments
$ kubectl auth can-i delete nodes